services:
  backend:
    build: ./backend
    ports:
      - "${PORT_BACKEND}:${PORT_BACKEND}"
    env_file:
      - .env
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "${PORT_FRONTEND}:${PORT_FRONTEND}"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
